# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strlen < Formula
  desc "An app that tells you the length of a string"
  homepage "https://github.com/marcos/strlen"
  version "0.0.1"
  license "BSD-3-Clause"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "af4a2040aedd4a8e2dc33323dee3223a10b80edc101a0e4f2318c3d117fddf1e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Darwin_arm64.tar.gz"
      sha256 "0c50817b84f7dea86222bbab4a98b377c304f1f219a4bcfb89cccd71e0393a7d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Linux_x86_64.tar.gz"
      sha256 "ccff1a0bbb876489795668ff955f9a2858089584e212614dfea12df006d0c004"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Linux_arm64.tar.gz"
      sha256 "5420ec72c73789292618a4ad803e8cedeee74e3013b102e751e3b2140648f487"
    end
  end

  def install
    bin.install "strlen"
  end
end
