# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strlen < Formula
  desc "An app that tells you the length of a string"
  homepage "https://github.com/marcos/strlen"
  version "0.0.1"
  license "BSD-3-Clause"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "7ee5155f440f9c9b9cf20dc4b9bcba5cb19bd1e928cac3ad48fc01f164bd38b4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Darwin_arm64.tar.gz"
      sha256 "b813209189eff6ddd8bf8ba23a6387c8fafeff2dc32166e279d7070030c10303"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Linux_x86_64.tar.gz"
      sha256 "4b06062e465497e988b5864aaaef2156153d6bd3dbd4751334728e5e9b33505e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Marcos/strlen/releases/download/v0.0.1/strlen_0.0.1_Linux_arm64.tar.gz"
      sha256 "edd9f35b01d9d387904d9689a13a87eaa17a5edc8b229d5525fa7d9c23e853a5"
    end
  end

  def install
    bin.install "strlen"
  end
end
